export const CONTACT_FORM_INIT = 'CONTACT_FORM_INIT';
export const CONTACT_FORM_ADD_DEFAULT_FIELD = 'CONTACT_FORM_ADD_DEFAULT_FIELD';
export const CONTACT_FORM_REMOVE_FIELD = 'CONTACT_FORM_REMOVE_FIELD';
